### PR TITLE
changed extensions according to latest version and updated readme and added some new words

### PR DESCRIPTION
**Pull request by shivanshsoni**
Please let me know if you want any other changes.

### CODE REVIEW

**Comment by Shubhamsharma09** [comment]
There is one important thing you can do for me, star my repo 😆

**Comment by shivanshsoni** [comment]
Ok bkl :-)

**Comment by Shubhamsharma09** [comment]
Please use appropriate language guddu 😆

**Comment by shivanshsoni** [comment]
@Shubhamsharma09 Ok narender

**Pull request merged**
